name: Scheduled Price Update

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:

jobs:
  update-price:
    concurrency:
      group: "scheduled-price-update"
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ensure the version matches your app's requirement

      - name: Install dependencies
        run: npm install

      - name: Run the update script
        run: node api/updatePrice.js  # Make sure this path is correct
        env:
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }} 
          COINGECKO_API_URL: ${{ secrets.COINGECKO_API_URL }}
